music/urls.py
from django.conf.urls import url

from . import views

from django.conf.urls import include, url
from django.contrib import admin
admin.autodiscover()
from django.views.generic import ListView
from music.models import Kategorija, Oglas

app_name = 'music'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #home page
    url(r'^$', views.index, name='index'),
    url(r'^(?P<selected_page>\d+)/?$', views.index, name='index_page'),
    url(r'^oglasi/(?P<slug>\w+)?$', views.DetailView.as_view(), name='detail'),
    url(r'^oglasi/(?P<slug>\w+)/wishlist_oglas/?$', views.wishlist_oglas, name='wishlist_oglas'),
    url(r'^oglasi/(?P<slug>\w+)/izbrisi_oglas/?$', views.Izbrisi_oglas.as_view(), name='izbrisi_oglas'),

    url(r'^kategorije/?$', ListView.as_view(
        model=Kategorija), name="list_kategorija"),
    url(r'^kategorije/(?P<kategorijaTitle>\w+)/?$', views.getKategorija, name='get_Kategorija'),
    url(r'^kategorije/(?P<kategorijaSlug>\w+)/(?P<selected_page>\d+)/?$', views.getKategorija, name='page_Kategorija'),


    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<oglas_id>[0-9]+)/$', views.getOglas, name='detailid'),
    url(r'^napravi_oglas/$', views.napravi_oglas, name='napravi_oglas'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^profile/(?P<username>[a-zA-Z0-9]+)/$', views.get_user_profile, name='get_user_profile'),
    url(r'^(?P<username>[a-zA-Z0-9]+)/oglasi/$', views.oglasi_korisnik, name='oglasi_korisnik'),
    url(r'^users/edit/$', views.edit_user, name="edit_profile"),
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^', include('music.urls')),
    url(r'^user/', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
from django.forms import HiddenInput, forms
from datetime import datetime
from django.contrib.auth.models import User

class Employee(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    broj = models.CharField(max_length=15)
    slika = models.FileField(default='defprofilepic.png')
    lokacija = models.CharField(max_length=40)

    def __str__(self):
        return self.user.username

class Kategorija(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=40, unique=True)
    description=models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Kategorije"

    def get_absolute_url(self):
        return "/kategorije/%s" % self.slug

class Oglas(models.Model):
    vlasnik = models.ForeignKey(User, default=1)
    ime_oglasa = models.CharField(max_length=500)
    slike = models.FileField()
    na_wishlist = models.BooleanField(default=False)
    datum_objave = models.DateTimeField(default=datetime.now, blank=True)
    opis=models.TextField(default='')
    grad=models.CharField(max_length=50, default='Sarajevo')
    cena=models.IntegerField(max_length=30, default=100)
    slug=models.SlugField(max_length=40, unique=True)
    kategorija = models.ForeignKey(Kategorija, default=1)
    KORISCENO = 'Korisceno'
    NOVO = 'Novo'
    STANJE_CHOICES = (
        (KORISCENO, 'Korisceno'),
        (NOVO, 'Novo'),
    )

    stanje = models.CharField(choices=STANJE_CHOICES, max_length=100, default=NOVO)
    def __str__(self):
        return self.ime_oglasa

    def get_absolute_url(self):
        return "/%s/%s/%s" %('music', 'oglasi', self.slug)

    class Meta:
        verbose_name_plural = "Oglasi"
        ordering = ["-datum_objave"]


class KategorijaToOglas(models.Model):
    oglas=models.ForeignKey(Oglas)
    kategorija=models.ForeignKey(Kategorija)

music/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Oglas, Employee
from datetime import datetime

class OglasForm(forms.ModelForm):

    class Meta:
        model = Oglas
        fields = ['ime_oglasa', 'slike', 'opis', 'cena', 'grad', 'kategorija', 'slug', 'stanje']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['slika', 'broj', 'lokacija']

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['broj', 'lokacija']

    def save(self, user=None):
        user_profile = super(UserProfileForm, self).save(commit=False)
        emp = Employee.objects.get(user=user)
        if user:
            user_profile.user = user
        user_profile.save()
        emp.save()
        return user_profile

class EditForm(forms.ModelForm):
    broj = forms.CharField(label="Broj:")
    lokacija = forms.CharField(label="Lokacija:")
    class Meta:
        model = Employee
        fields = ['slika', 'broj', 'lokacija']

music/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .forms import OglasForm, UserForm, EmployeeForm, UserProfileForm, EditForm
from .models import Oglas, Kategorija, Employee
from django.contrib.auth.models import User
from django.shortcuts import render_to_response
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template import RequestContext
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy, reverse
from django.views.generic import View


AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


def napravi_oglas(request):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        form = OglasForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            oglas = form.save(commit=False)
            oglas.vlasnik = request.user
            oglas.slike = request.FILES['slike']
            file_type = oglas.slike.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'oglas': oglas,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'music/napravi_oglas.html', context)
            oglas.save()
            return render(request, 'music/detail.html', {'oglas': oglas})
        context = {
            "form": form,
            'kategorije': Kategorija.objects.all(),
        }
        return render(request, 'music/napravi_oglas.html', context)
"""
def izbrisi_oglas(request, id):
    oglas = Oglas.objects.get(pk=id)
    oglas.delete()
    oglasi = Oglas.objects.filter(vlasnik=request.user)
    return render_to_response('music/index.html', {'oglasi': oglasi}, RequestContext(request))
"""

class Izbrisi_oglas(DeleteView):
    model = Oglas
    success_url = reverse_lazy('music:index')


def detail(request, slug):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        vlasnik = request.user
        oglas1 = Oglas.objects.filter(slug=slug)
        return render(request, 'music/detail.html', {'oglasi': oglas1, 'vlasnik': vlasnik, 'kategorije': Kategorija.objects.all()})


def wishlist_oglas(request, oglas_id):
    oglas = get_object_or_404(Oglas, pk=oglas_id)
    try:
        if oglas.na_wishlist:
            oglas.na_wishlist = False
        else:
            oglas.na_wishlist = True
        oglas.save()
    except (KeyError, Oglas.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})
"""
def index(request, selected_page=1):
    oglasi = Oglas.objects.all().order_by('-datum_objave')
    pages=Paginator(oglasi, 5)
    returned_page=pages.page(selected_page)

    try:
        returned_page=pages.page(selected_page)
    except EmptyPage:
        returned_page=pages.page(pages.num_pages)

    return render(request, 'music/index.html', { 'oglasi':returned_page.object_list , 'kategorije' : Kategorija.objects.all(), 'request' : request})

"""
def index(request):
    queryset_list = Oglas.objects.all().order_by('-datum_objave')
    query = request.GET.get("ime")
    if query:
        queryset_list = queryset_list.filter(
            Q(ime_oglasa__icontains=query) |
            Q(opis__icontains=query)
        ).distinct()

    query = request.GET.get("grad")
    if query:
        queryset_list = queryset_list.filter(
            Q(grad__icontains=query)
        ).distinct()

    query = request.GET.get("cenaOd")
    if query:
        queryset_list = queryset_list.filter(
            Q(cena__gte=query)
        ).distinct()

    query = request.GET.get("cenaDo")
    if query:
        queryset_list = queryset_list.filter(
            Q(cena__lte=query)
        ).distinct()

    query = request.GET.get("kategorija")
    if query:
        kategorijasearch = Kategorija.objects.filter(title=query)
        queryset_list = queryset_list.filter(
            Q(kategorija=kategorijasearch)
        ).distinct()

    if queryset_list == Oglas.objects.all():
        queryset_list = {}

    paginator = Paginator(queryset_list, 8)  # Show 25 contacts per page
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    context = {
        "oglasi": queryset,
        "page_request_var": page_request_var,
        "kategorije": Kategorija.objects.all(),
    }
    return render(request, "music/index.html", context)


def getOglas(request, oglasSlug):
    oglas=Oglas.objects.filter(slug=oglasSlug)

    return render_to_response('music/single.html', { 'oglas': oglas, 'kategorije': Kategorija.objects.all()}, context_instance=RequestContext(request))

def getKategorija(request, kategorijaTitle):
    """
    kategorija_oglasi=[]
    for oglas in oglasi:
        if oglas.kategorije.filter(slug=kategorijaSlug):
            kategorija_oglasi.append(oglas)

    pages=Paginator(kategorija_oglasi, 5)

    try:
        returned_page=pages.page(selected_page)
    except EmptyPage:
"""
    kategorija = Kategorija.objects.filter(title=kategorijaTitle)
    oglasi = Oglas.objects.filter(kategorija=kategorija)

    paginator = Paginator(oglasi, 8)  # Show 25 contacts per page
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    return render_to_response('music/kategorija.html', {'oglasi' : queryset, #'page':returned_page,
      'kategorija' : kategorijaTitle, 'kategorije': Kategorija.objects.all(), "page_request_var": page_request_var})

class DetailView(generic.DetailView):
    model = Oglas
    template_name = 'music/detail.html'
    
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(DetailView, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['kategorije'] = Kategorija.objects.all()
        return context

"""
def index(request):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
       
            return render(request, 'music/index.html', {
                'oglasi': oglasi,
            })
        else:
            return render(request, 'music/index.html', {'oglasi': oglasi})

"""
def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
        'kategorije': Kategorija.objects.all()
    }
    return render(request, 'music/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                oglasi = Oglas.objects.filter(vlasnik=request.user)
                return render(request, 'music/index.html', {'oglasi': oglasi})
            else:
                return render(request, 'music/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'music/login.html', {'error_message': 'Invalid login'})
    return render(request, 'music/login.html')


def register(request):
    uform = UserForm(request.POST or None)
    pform = EmployeeForm(request.POST or None)
    if uform.is_valid() and pform.is_valid():
        user = uform.save(commit=False)
        username = uform.cleaned_data['username']
        password = uform.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        profile = pform.save(commit=False)
        if (request.FILES):
            profile.slika = request.FILES['slika']
        profile.user = user
        profile.save()
        if user is not None:
            if user.is_active:
                login(request, user)
                oglasi = Oglas.objects.filter(vlasnik=request.user)
                return render(request, 'music/index.html', {'oglasi': oglasi})
    context = {
        "form": uform,
        "pform" : pform,
        "kategorije": Kategorija.objects.all(),
    }
    return render(request, 'music/register.html', context)


def faq(request):
    return render(request, 'music/faq.html', {'kategorije': Kategorija.objects.all()})


def get_user_profile(request, username):
    user = User.objects.get(username=username)
    oglasi = Oglas.objects.filter(vlasnik=user)
    emp = Employee.objects.filter(user=user)
    if len(emp) > 0:
        employee = emp[0]
    else:
        employee = False

    paginator = Paginator(oglasi, 8)  # Show 25 contacts per page
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Oglasi.ba{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'music/js/main.js' %}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
</head>
<body>
<div class="container">
<nav class="navbar navbar-default">
    <a class="navbar-brand" href="{% url 'music:index' %}"><img src="../../static/music/images/logoic.png" alt="eyy"></a>
    <ul class="nav navbar-nav">
            <li class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownKategorije" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                ☰&nbsp;Kategorije
                    <span class="caret"></span>
                </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownKategorije" >
                {% for kategorij in kategorije %}
                  <li><a href="{% url 'music:get_Kategorija' kategorij %}"> {{ kategorij.title }} </a></li>
                  {% endfor %}
              </ul>
            </li>
        <li class="nav-item">
            <p class="navbar-btn">
                <a href="{% url 'music:napravi_oglas' %}" class="btn btn-success" id="postaviOglas">+ Postavi oglas</a>
            </p>
        </li>
    </ul>
    <ul class="nav navbar-nav pull-right">
        {% if not user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'music:login_user' %}">Login</a>
            </li>
        {% endif %}
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'music:edit_profile' %}">Edit profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'music:logout_user' %}">Logout</a>
            </li>
        {% endif %}
        {% if not user.is_authenticated %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'music:register' %}">Register</a>
        </li>
        {% endif %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'music:faq' %}">FAQ</a>
        </li>
    </ul>
    </nav>
    <div class="container">
        <form class="form">
            <div class="col-sm-9">
                <div class="form-group">
                    <input type="text" name="ime" class="form-control" id="text" value="{{ request.GET.ime }}">
                </div>
            </div>
            <div class="col-sm-2">
                <select name="kategorija">
                    <option value="">
                    {% if request.GET.kategorija %}
                        {{ request.GET.kategorija }}
                    {% else %}
                        Izaberite kategoriju
                    {% endif %}
                    </option>
                    {% for kategorija in kategorije %}
                        <option value="{{ kategorija.title }}">{{ kategorija.title }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-sm-1">
                <button type="submit" class="btn btn-default">Search</button>
            </div>
		</form>
    </div>
</nav>
</div>
<br>
<div class="container">
{% block body %}
{% endblock %}
</div>
<br>
<br>
<div class="container">
    <div class="pagination">
<div class="pagination">
    <span class="step-links">
        {% if oglasi.has_previous %}
            <a href="?{{ page_request_var }}={{ oglasi.previous_page_number }}{% if request.GET.ime %}&ime={{ request.GET.ime }}{% endif %}
                                                                                   {% if request.GET.kategorija %}&kategorija={{ request.GET.kategorija }}{% endif %}
                                                                                   {% if request.GET.cenaOd %}&cenaOd={{ request.GET.cenaOd }}{% endif %}
                                                                                   {% if request.GET.cenaDo %}&cenaDo={{ request.GET.cenaDo }}{% endif %}
                                                                                   {% if request.GET.grad %}&grad={{ request.GET.grad }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ oglasi.number }} of {{ oglasi.paginator.num_pages }}.
        </span>

        {% if oglasi.has_next %}
            <a href="?{{ page_request_var }}={{ oglasi.next_page_number }}{% if request.GET.ime %}&ime={{ request.GET.ime }}{% endif %}
                                                                                   {% if request.GET.kategorija %}&kategorija={{ request.GET.kategorija }}{% endif %}
                                                                                   {% if request.GET.cenaOd %}&cenaOd={{ request.GET.cenaOd }}{% endif %}
                                                                                   {% if request.GET.cenaDo %}&cenaDo={{ request.GET.cenaDo }}{% endif %}
                                                                                   {% if request.GET.grad %}&grad={{ request.GET.grad }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>
</div>
<div class="container text-center" id="footer">
<br>
        Ovo je krajnje profesionalan sait
        <br>
        Napravljen sa preciznoscu
<div class="container text-right" id="footer">
        Eyy
</div>
</body>
</html>

music/templates/music/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Oglasi.ba{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'music/js/main.js' %}"></script>
    <style>
		

	</style>
</head>
<body>
<div class="container">
<nav class="navbar navbar-default">
    <a class="navbar-brand" href="{% url 'music:index' %}"><img src="www.stralz.com/novi/logoic.png" alt="eyy"></a>
    <ul class="nav navbar-nav">
            <li class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownKategorije" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                ☰&nbsp;Kategorije
                    <span class="caret"></span>
                </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownKategorije" >
                {% for kategorij in kategorije %}
                  <li><a href="{% url 'music:get_Kategorija' kategorij %}"> {{ kategorij.title }} </a></li>
                  {% endfor %}
              </ul>
            </li>
        <li class="nav-item">
            <p class="navbar-btn">
                <a href="{% url 'music:napravi_oglas' %}" class="btn btn-success" id="postaviOglas">+ Postavi oglas</a>
            </p>
        </li>
    </ul>
    <ul class="nav navbar-nav pull-right">
        {% if not user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'music:login_user' %}">Login</a>
            </li>
        {% endif %}
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'music:edit_profile' %}">Edit profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'music:logout_user' %}">Logout</a>
            </li>
        {% endif %}
        {% if not user.is_authenticated %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'music:register' %}">Register</a>
        </li>
        {% endif %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'music:faq' %}">FAQ</a>
        </li>
    </ul>
    </nav>
<!--
			<form class="form-inline">
			  <div class="form-group">
			    <label for="email">Ime artikla:</label>
			    <input type="text" class="form-control" id="text">
			  </div>
			  <div class="form-group">
			  	<select>
			  		<option value="Kompljuteri">Kompljuteri</option>
			  		<option value="Saab">Saab</option>
			  		<option value="Opel">Opel</option>
			  		<option value="Audi">Audi</option>
			  	</select>
			  </div>
                <div class="input-group">
                    <span class="input-group-addon">cena od</span>
                    <input id="msg" type="text" class="form-control" name="msg" placeholder="Min cena">
                </div>
                <div class="input-group">
                    <span class="input-group-addon">do</span>
                    <input id="msg" type="text" class="form-control" name="msg" placeholder="Max cena">
                </div>
                <div class="form-group">
                    <input type="text" placeholder="Grad">
                </div>
			  <button type="submit" class="btn btn-default">Search</button>
			</form>
-->
</nav>
</div>
<br>
<div class="container">
{% block body %}
{% endblock %}
</div>
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}{{ oglas }}{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <!-- Left Album Info -->
        <div class="col-sm-8 col-md-9">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a class=" "href="{% url 'music:detail' oglas.slug %}">
                        {% if oglas.slike %}
                            <img src="{{ oglas.slike.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ oglas.ime_oglasa }}</h1>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    Vlasnik: <br>
                    <a href="{% url 'music:get_user_profile' oglas.vlasnik %}">{{ oglas.vlasnik }}</a> (broj oglasa)
                    <br>
                    <a href="{% url 'music:oglasi_korisnik' oglas.vlasnik %}">svi oglasi</a>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<div class="container">
    <div class="panel panel-default">
        <div class="panel-body">
            kategorija: {{ oglas.kategorija }}
            <br>
            stanje: {{ oglas.stanje }}
            <br>
            opis: <br>{{ oglas.opis }}
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/faq.html
faq

music/templates/music/form_template.html
<!-- glavne informacije -->
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}
<!-- dodatne informacije -->
{% if pform %}
    {% for field in pform %}
        {% if field.label == "Broj:" %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <span class="text-danger small"></span>
            </div>
            <label class="control-label col-sm-2" for="song_title"><label for="id_broj">Broj:</label></label>
            <div class="col-sm-10"><input type="text" name="broj" required id="id_broj" maxlength="15" value="{{ br }}" /></div>
        </div>
        {% elif field.label == "Lokacija:" %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <span class="text-danger small"></span>
            </div>
            <label class="control-label col-sm-2" for="song_title"><label for="id_lokacija">Lokacija:</label></label>
            <div class="col-sm-10"><input type="text" name="lokacija" required id="id_lokacija" maxlength="40" value="{{ lok }}" /></div>
        </div>
        {% else %}
         <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <span class="text-danger small">{{ field.errors }}</span>
            </div>
            <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
            <div class="col-sm-10">{{ field }}</div>
        </div>
        {% endif %}
    {% endfor %}
{% endif %}